name: 'Build and Release'
description: 'Build and release tools for Windows'
inputs:
  tool-name:
    description: 'tool name'
    required: true
  tool-version:
    description: 'tool version'
    required: true
  artifact-name:
    description: 'Artifact name (e.g., "tool-name-x.x-windows-x86-64.zip")'
    required: true
  release-token:
    description: 'Token for GitHub release'
    required: true
  tool-dependencies:
    description: 'Dependencies required for the tool, separated by spaces (e.g., "dos2unix grep")'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      name: Check out source code

    - name: Install Dependencies
      shell: bash
      run: |
        if command -v sudo >/dev/null; then
          if [ ! -z "${{ inputs.tool-dependencies }}" -a "${{ inputs.tool-dependencies }}" != " " ]; then
            echo "Updating apt package list..."
            sudo apt-get update > /dev/null
            echo "Installing dependencies: ${{ inputs.tool-dependencies }}"
            sudo apt-get install -y ${{ inputs.tool-dependencies }} > /dev/null
          else
            echo "No dependencies to install."
          fi
        else
          echo "sudo not available, skipping dependency installation."
        fi

    - name: Build ${{ inputs.tool-name }}
      shell: bash
      run: |
        cd script && ./${{ inputs.tool-name }}.sh

    - name: Upload Build to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/dist/${{ inputs.artifact-name }}
        name: ${{ github.ref_name }}
        body: 'Release of ${{ github.ref_name }}'
        draft: false
        prerelease: false
        token: ${{ inputs.release-token }}
